{
echo "SECRET_KEY=$APP_KEY"
echo "ALGORITHM=HS256"
echo "ACCESS_TOKEN_EXPIRES_IN=$ACCESS_TOKEN_EXPIRES_IN"
echo "DB_USER=$DB_USER"
echo "DB_PASSWORD=$DB_PASSWORD"
echo "DB_NAME=$DB_NAME"
echo "DB_HOST=$DB_HOST"
echo "DB_PORT=$DB_PORT"
echo "SERVER_URL=$SERVER_URL"
} >> .env