services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  certbot:
    build:
      context: .
      dockerfile: certbot.dockerfile
    depends_on:
      nginx:
        condition: service_started
    volumes:
      - ./certbot-entrypoint.sh:/entrypoint.sh
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      - DOMAIN=${SERVER_URL}
      - EMAIL=anton@anton.eco

  nginx:
    image: nginx
    restart: always
    depends_on:
      api:
        condition: service_started
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./alembic:/var/www/api/alembic
      - ./app:/var/www/api/app
      - ./.env:/var/www/api/.env
      - ./requirements.txt:/var/www/api/requirements.txt
      - ./alembic.ini:/var/www/api/alembic.ini
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  dbdata:
  myapp:
  certbot-etc:
  certbot-var: