version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5432:5432"
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fast-api

  api:
    image: bitnami/python
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:8000"
    working_dir: /var/www/api
    volumes:
      - ./alembic:/var/www/api/alembic
      - ./app:/var/www/api/app
      - ./.env:/var/www/api/.env
      - ./requirements.txt:/var/www/api/requirements.txt
    command: bash -c 'apt-get update && apt-get install -y postgresql libpq-dev && pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000'