services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./alembic:/var/www/api/alembic
      - ./app:/var/www/api/app
      - ./.env:/var/www/api/.env
      - ./requirements.txt:/var/www/api/requirements.txt
      - ./alembic.ini:/var/www/api/alembic.ini
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"

volumes:
  dbdata:
  myapp: