name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Generate .env file
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: chmod +x ./create_env.sh && ./create_env.sh

    - name: SSH to server and clone the repository
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP << EOF
          docker-compose down
          rm -rf /var/www && mkdir /var/www
          git clone https://github.com/hrsa/py-fastapi.git /var/www
          EOF

    - name: Modify nginx config
      env:
        SERVER_IP:  ${{ secrets.SERVER_IP }}
        SERVER_NAME: ${{ secrets.SERVER_IP }}
      run: |
          ssh -o StrictHostKeyChecking=no root@$SERVER_IP << EOF
          echo "${SERVER_NAME}" > server_name.txt
          sed -i 's/localhost/$(cat server_name.txt)/g' /var/www/nginx-config.conf
          rm server_name.txt
          EOF

    - name: Copy .env file to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        scp -o StrictHostKeyChecking=no .env root@$SERVER_IP:/var/www

    - name: Start docker compose
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: ssh -o StrictHostKeyChecking=no root@$SERVER_IP "cd /var/www && docker-compose up --build -d"